### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by pwnchief** [chrispetrou/FDsploit#1]
pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting bs4
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting hashlib
  Using cached https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
    ERROR: Command errored out with exit status 1:
     command: /Users/pwnchief/.virtualenvs/fdsploit/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5f/kxv0g0091q57d96wp0ybvlqw0000gn/T/pip-install-9E0aFC/hashlib/setup.py'"'"'; __file__='"'"'/private/var/folders/5f/kxv0g0091q57d96wp0ybvlqw0000gn/T/pip-install-9E0aFC/hashlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5f/kxv0g0091q57d96wp0ybvlqw0000gn/T/pip-install-9E0aFC/hashlib/pip-egg-info
         cwd: /private/var/folders/5f/kxv0g0091q57d96wp0ybvlqw0000gn/T/pip-install-9E0aFC/hashlib/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/pwnchief/.virtualenvs/fdsploit/lib/python2.7/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/Users/pwnchief/.virtualenvs/fdsploit/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/Users/pwnchief/.virtualenvs/fdsploit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
        import email.parser
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/feedparser.py", line 27, in <module>
        from email import message
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/message.py", line 16, in <module>
        import email.charset
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/charset.py", line 13, in <module>
        import email.base64mime
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/base64mime.py", line 40, in <module>
        from email.utils import fix_eols
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/utils.py", line 27, in <module>
        import random
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
        import hashlib as _hashlib
      File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dabula-s** [comment]
try to remove hashlib and urlparse from requirements.txt. both are built in libraries
